version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-telegram_db}
      - DB_USER=${DB_USER:-telegram_user}
      - DB_PASSWORD=${DB_PASSWORD:-telegram_password}
    volumes:
      - ./session_files:/app/session_files
    
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-telegram_db}
      - MYSQL_USER=${DB_USER:-telegram_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-telegram_password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
