name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true  # Don't fail the build for linting issues
    
    - name: Check code formatting
      run: |
        pip install black
        black --check .
      continue-on-error: true  # Don't fail the build for formatting issues

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: deploy
    
    steps:
    - uses: actions/checkout@v3
    
    # Deploy using SSH (simple version with no conditionals)
    - name: Deploy via SSH with password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd $HOME
          echo "=== DEPLOYMENT STARTED: $(date) ==="
          
          # Set project directory
          PROJECT_DIR="$HOME/telegram-listener"
          
          # Create directory if it doesn't exist
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "Creating project directory..."
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"
            git clone https://github.com/chanhengseang3/telegram-listener.git .
            echo "Repository cloned"
          else
            # Update existing repository
            cd "$PROJECT_DIR"
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            echo "Repository updated"
          fi
          
          # Install dependencies
          echo "Installing dependencies..."
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          echo "Dependencies installed"
          
          # Stop any existing bot processes
          echo "Stopping any existing bot processes..."
          pkill -f "python.*main.py" || echo "No processes found to stop"
          sleep 2
          
          # Start the bot
          echo "Starting the bot..."
          cd "$PROJECT_DIR"
          nohup python3 main.py > bot.log 2>&1 &
          sleep 2
          
          # Verify bot is running
          if pgrep -f "python.*main.py"; then
            echo "Bot started successfully"
          else
            echo "Failed to start bot. Check logs."
            tail -20 bot.log
            exit 1
          fi
          
          echo "=== DEPLOYMENT COMPLETED: $(date) ==="
